export const TASK_SOURCE_PLUGINS = Symbol("TASK_SOURCE_PLUGINS");
export const TASK_RESULT_REPORTER_PLUGINS = Symbol("TASK_RESULT_REPORTER_PLUGINS");
export const EXECUTION_ENGINE_PLUGIN = Symbol("EXECUTION_ENGINE_PLUGIN");
export const AGENT_RUNTIME_PLUGIN = Symbol("AGENT_RUNTIME_PLUGIN");
