import { mkdir, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { EnvironmentContext, EnvironmentPlugin, PluginHealth, PreparedWorkspace, TitingTask } from "@titing/plugin-api";
import { ServerConfig } from "../config";
import {
  EnvironmentPreparationError,
  hashRepo,
  installDependenciesIfNeeded,
  isAutoGeneratedTaskBranch,
  normalizeWorkspaceEnv,
  pathExists,
  resolveBranchRef,
  runCheckedCommand
} from "./shared";

/**
 * Prepares an isolated git worktree per task from a shared mirror cache under `repoCacheRoot`, then optional `npm install`.
 * Cleanup is fully gated by `cleanupOnSuccess` / `cleanupOnFailure`; when disabled, the repo worktree and task workspace are preserved.
 */
export class LocalWorktreeEnvironmentPlugin implements EnvironmentPlugin {
  readonly id = "git-worktree-local";
  readonly kind = "environment" as const;
  readonly priority = 100;
  readonly capabilities = ["local-worktree"];

  constructor(private readonly config: ServerConfig) {}

  /** Reflects configured workspace root; does not probe git. */
  async health(): Promise<PluginHealth> {
    return { healthy: true, message: `Workspace root ${this.config.workspace.root}` };
  }

  /**
   * Workspace pipeline: mkdir layout → clone-or-fetch mirror → remove stale worktree → resolve branch ref →
   * `worktree add` + checkout → install deps if `package.json` exists → write `artifacts/workspace.json`.
   */
  async prepareWorkspace(task: TitingTask, context?: EnvironmentContext): Promise<PreparedWorkspace> {
    const workspacePath = resolve(this.config.workspace.root, `${task.id}-${task.executor}`);
    const repoPath = join(workspacePath, "repo");
    const artifactsPath = join(workspacePath, "artifacts");
    const cachePath = resolve(this.config.workspace.repoCacheRoot, hashRepo(task.repo));
    const env = normalizeWorkspaceEnv(task.metadata.env);

    await mkdir(workspacePath, { recursive: true });
    await mkdir(this.config.workspace.repoCacheRoot, { recursive: true });
    await mkdir(artifactsPath, { recursive: true });

    if (await pathExists(cachePath)) {
      await this.removeRegisteredWorktree(cachePath, repoPath, context);
    }
    if (!(await pathExists(cachePath))) {
      await runCheckedCommand(
        "git",
        ["clone", "--mirror", task.repo, cachePath],
        this.config.workspace.root,
        process.env,
        this.config.goalRecovery.executionTimeoutMs,
        "clone",
        context?.runtimeLogger
      );
    } else {
      await runCheckedCommand(
        "git",
        [
          "--git-dir",
          cachePath,
          "fetch",
          "origin",
          "--prune",
          "+refs/heads/*:refs/remotes/origin/*",
          "+refs/tags/*:refs/tags/*"
        ],
        this.config.workspace.root,
        process.env,
        this.config.goalRecovery.executionTimeoutMs,
        "fetch",
        context?.runtimeLogger
      );
    }

    await rm(repoPath, { recursive: true, force: true });
    const targetRef = await this.resolveWorkspaceTargetRef(cachePath, task);
    await runCheckedCommand(
      "git",
      ["--git-dir", cachePath, "worktree", "add", "--force", repoPath, targetRef],
      this.config.workspace.root,
      process.env,
      this.config.goalRecovery.executionTimeoutMs,
      "worktree",
      context?.runtimeLogger
    );
    await runCheckedCommand(
      "git",
      ["-C", repoPath, "checkout", "-B", task.branch, targetRef],
      this.config.workspace.root,
      process.env,
      this.config.goalRecovery.executionTimeoutMs,
      "checkout",
      context?.runtimeLogger
    );

    await installDependenciesIfNeeded(repoPath, env, this.config.goalRecovery.executionTimeoutMs, context?.runtimeLogger);
    await writeFile(join(artifactsPath, "workspace.json"), JSON.stringify({
      taskId: task.id,
      repo: task.repo,
      branch: task.branch,
      preparedAt: new Date().toISOString(),
      envKeys: Object.keys(env)
    }, null, 2));

    return {
      workspacePath,
      repoPath,
      branch: task.branch,
      cachePath,
      artifactsPath,
      env
    };
  }

  /**
   * Best-effort `git worktree remove` using the mirror at `workspace.cachePath`, then rimraf the task folder.
   * When cleanup is disabled for the terminal status, preserve the full workspace including the repo worktree.
   */
  async cleanupWorkspace(task: TitingTask, workspace: PreparedWorkspace): Promise<void> {
    const shouldDelete =
      (task.status === "done" && this.config.workspace.cleanupOnSuccess) ||
      (task.status !== "done" && this.config.workspace.cleanupOnFailure);
    if (!shouldDelete) {
      return;
    }

    try {
      await this.removeRegisteredWorktree(workspace.cachePath, workspace.repoPath);
    } finally {
      await rm(workspace.workspacePath, { recursive: true, force: true });
    }
  }

  private async removeRegisteredWorktree(
    cachePath: string,
    repoPath: string,
    context?: EnvironmentContext
  ): Promise<void> {
    try {
      await runCheckedCommand(
        "git",
        ["--git-dir", cachePath, "worktree", "remove", "--force", repoPath],
        this.config.workspace.root,
        process.env,
        this.config.goalRecovery.executionTimeoutMs,
        "cleanup",
        context?.runtimeLogger
      );
    } catch (error) {
      if (!(error instanceof EnvironmentPreparationError) || error.stage !== "cleanup") {
        throw error;
      }
    }
  }

  private async resolveWorkspaceTargetRef(cachePath: string, task: TitingTask): Promise<string> {
    try {
      return await resolveBranchRef(cachePath, task.branch, this.config.goalRecovery.executionTimeoutMs);
    } catch (error) {
      if (!(error instanceof EnvironmentPreparationError) || error.stage !== "checkout") {
        throw error;
      }
      if (!isAutoGeneratedTaskBranch(task.metadata)) {
        throw error;
      }
      try {
        return await resolveBranchRef(cachePath, "main", this.config.goalRecovery.executionTimeoutMs);
      } catch (fallbackError) {
        if (fallbackError instanceof EnvironmentPreparationError && fallbackError.stage === "checkout") {
          throw new EnvironmentPreparationError(
            "checkout",
            `Default task branch ${task.branch} could not be created from origin/main`,
            fallbackError.detail,
            false
          );
        }
        throw fallbackError;
      }
    }
  }
}

export { EnvironmentPreparationError } from "./shared";
