/**
 * Titing **领域门面**：聚合仓储、`PluginRuntime`、任务命令/查询与后台调度。
 *
 * - **本类**：任务与 Agent 生命周期、可观测读模型（trace/dashboard）、插件配置 API；
 *   将周期调度委托给 `ServiceScheduler`。
 * - **内部协作**：`ServiceSupport`（迁移+日志+事件）、`ServiceExecution`（单次执行与质量/修复）、
 *   `ServiceScheduler`（拉单、离线恢复、`queued`→`running`）。
 * - **细粒度门面**（便于客户端只依赖子集）：`taskCommands`、`taskQueries`、`scheduler`、
 *   `repairLoop`、`humanIntervention`、`pluginAdmin`；`executionOrchestrator` 为薄适配层。
 *
 * @see ServiceDependencies
 */
import {
  AgentRecord,
  CreateTaskInput,
  EvalResult,
  ExecutionLogRecord,
  ExecutionRecord,
  PluginConfig,
  RepairGoal,
  TaskListQuery,
  TaskTransition,
  TitingTask
} from "@titing/plugin-api";
import { randomUUID } from "node:crypto";
import { NotFoundError } from "./errors";
import { ExecutionOrchestrator } from "./execution-orchestrator";
import { HumanInterventionService } from "./human-intervention-service";
import { PluginAdminService } from "./plugin-admin-service";
import { RepairLoopService } from "./repair-loop-service";
import { SchedulerService } from "./scheduler-service";
import { TaskCommandService } from "./task-command-service";
import { TaskQueryService } from "./task-query-service";
import {
  attachBranchMetadata,
  buildDefaultTaskBranch,
  countBy,
  normalizeOptionalBranch,
  ServiceConfig,
  ServiceDependencies
} from "./service-shared";
import { ServiceSupport } from "./service-support";
import { ServiceExecution } from "./service-execution";
import { ServiceScheduler } from "./service-scheduler";

export type { ServiceDependencies } from "./service-shared";

/**
 * 对外业务能力入口；`OBSERVABILITY_SCHEMA_VERSION` 与执行日志/事件信封对齐。
 */
export class TitingServices {
  /** 可观测 API（getTraceView、getTaskObservability 等）返回结构中的 schema 版本号。 */
  static readonly OBSERVABILITY_SCHEMA_VERSION = "2026-05-11";

  /** 只含写操作的任务 API，与 `taskQueries` 对称，便于权限拆分。 */
  readonly taskCommands: TaskCommandService;
  readonly taskQueries: TaskQueryService;
  readonly scheduler: SchedulerService;
  readonly executionOrchestrator: ExecutionOrchestrator;
  readonly repairLoop: RepairLoopService;
  readonly humanIntervention: HumanInterventionService;
  readonly pluginAdmin: PluginAdminService;

  private readonly config: ServiceConfig;
  private readonly support: ServiceSupport;
  private readonly execution: ServiceExecution;
  private readonly schedulerEngine: ServiceScheduler;

  /**
   * 注入仓储与运行时；可选字段见 `ServiceDependencies`（时钟、ID、重试上限等用于测试或调参）。
   */
  constructor(private readonly deps: ServiceDependencies) {
    const now = deps.now ?? (() => new Date());
    const createId = deps.createId ?? (() => randomUUID());
    const agentOfflineTimeoutMs = deps.agentOfflineTimeoutMs ?? 5 * 60 * 1000;

    this.config = {
      now,
      createId,
      agentOfflineTimeoutMs,
      environmentRetryLimit: deps.environmentRetryLimit ?? 2,
      executionRetryLimit: deps.executionRetryLimit ?? 2,
      maxRepairIterations: deps.maxRepairIterations ?? 3,
      enableNeedsHumanLoop: deps.enableNeedsHumanLoop ?? false,
      executionHeartbeatIntervalMs: deps.executionHeartbeatIntervalMs ?? Math.max(1_000, Math.floor(agentOfflineTimeoutMs / 3)),
      setIntervalFn: deps.setIntervalFn ?? ((callback, ms) => setInterval(callback, ms)),
      clearIntervalFn: deps.clearIntervalFn ?? ((timer) => clearInterval(timer as NodeJS.Timeout))
    };

    this.support = new ServiceSupport(deps, this.config, TitingServices.OBSERVABILITY_SCHEMA_VERSION);
    this.execution = new ServiceExecution(deps, this.config, this.support);
    this.schedulerEngine = new ServiceScheduler(deps, this.config, this.support, this.execution, this);

    this.taskCommands = new TaskCommandService(this);
    this.taskQueries = new TaskQueryService(this);
    this.scheduler = new SchedulerService(this as unknown as ConstructorParameters<typeof SchedulerService>[0]);
    this.executionOrchestrator = new ExecutionOrchestrator(this);
    this.repairLoop = new RepairLoopService(this);
    this.humanIntervention = new HumanInterventionService(this);
    this.pluginAdmin = new PluginAdminService(this);
  }

  /** 创建任务：补全 trace、默认分支名与 `metadata.titing.branch.autoGenerated` 标记。 */
  async createTask(input: CreateTaskInput): Promise<TitingTask> {
    const now = this.support.now();
    const id = this.support.createId();
    const normalizedBranch = normalizeOptionalBranch(input.branch);
    const branch = normalizedBranch ?? buildDefaultTaskBranch(id, now);
    const metadata = attachBranchMetadata(input.metadata, normalizedBranch === null);
    const task: TitingTask = {
      id,
      source: input.source ?? "manual",
      externalId: input.externalId ?? null,
      title: input.title,
      instruction: input.instruction,
      repo: input.repo,
      branch,
      priority: input.priority ?? "medium",
      status: "created",
      executor: input.executor ?? "codex",
      traceId: this.support.createId(),
      constraints: input.constraints ?? [],
      acceptanceCriteria: input.acceptanceCriteria ?? [],
      metadata,
      retryCount: 0,
      repairCount: 0,
      startedAt: null,
      completedAt: null,
      createdAt: now,
      updatedAt: now
    };
    await this.deps.tasks.create(task);
    await this.support.emitStatus(task, "created", "Task created", "system");
    return task;
  }

  /** 按状态/执行器过滤；无参返回全部（慎用大数据集）。 */
  async listTasks(query: TaskListQuery = {}): Promise<TitingTask[]> {
    return this.deps.tasks.list(query);
  }

  async getTask(id: string): Promise<TitingTask> {
    const task = await this.deps.tasks.getById(id);
    if (!task) {
      throw new NotFoundError(`Task ${id} not found`);
    }
    return task;
  }

  /**
   * 校验必填字段后转 `validated`；失败则 `failed`。常用于入队前的网关校验。
   */
  async validateTask(id: string, operator = "system"): Promise<TitingTask> {
    const task = await this.getTask(id);
    if (!task.instruction.trim() || !task.repo.trim() || !task.branch.trim()) {
      return this.support.transitionTask(task, "failed", "Task validation failed", operator);
    }
    return this.support.transitionTask(task, "validated", "Task validated", operator);
  }

  async queueTask(id: string, operator = "system"): Promise<TitingTask> {
    const task = await this.getTask(id);
    const ready = task.status === "created" ? await this.validateTask(id, operator) : task;
    const pending = ready.status === "validated"
      ? await this.support.transitionTask(ready, "pending", "Task moved to pending", operator)
      : ready;
    return this.support.transitionTask(pending, "queued", "Task queued", operator);
  }

  /**
   * 从终局态回到 `queued`：递增 `retryCount`，清空起止时间。
   */
  async retryTask(id: string, operator = "system"): Promise<TitingTask> {
    const task = await this.getTask(id);
    if (!["failed", "needs_human", "blocked"].includes(task.status)) {
      throw new Error(`Task ${task.id} cannot be retried from ${task.status}`);
    }
    task.retryCount += 1;
    task.startedAt = null;
    task.completedAt = null;
    task.updatedAt = this.support.now();
    await this.deps.tasks.save(task);
    return this.support.transitionTask(task, "queued", "Task retried", operator);
  }

  async blockTask(id: string, reason = "Task blocked by operator", operator = "system"): Promise<TitingTask> {
    const task = await this.getTask(id);
    if (!["created", "validated", "pending", "queued", "running"].includes(task.status)) {
      throw new Error(`Task ${task.id} cannot be blocked from ${task.status}`);
    }
    return this.support.transitionTask(task, "blocked", reason, operator);
  }

  async markNeedsHuman(
    id: string,
    reason = "Task requires human intervention",
    operator = "system"
  ): Promise<TitingTask> {
    const task = await this.getTask(id);
    if (!["evaluating", "repairing", "queued", "running"].includes(task.status)) {
      throw new Error(`Task ${task.id} cannot be marked needs_human from ${task.status}`);
    }
    const updatedTask = await this.support.transitionTask(task, "needs_human", reason, operator);
    updatedTask.completedAt = this.support.now();
    await this.deps.tasks.save(updatedTask);
    return updatedTask;
  }

  async recoverTask(
    id: string,
    operator = "system",
    reason = "Task manually recovered to queue"
  ): Promise<TitingTask> {
    const task = await this.getTask(id);
    if (!["blocked", "needs_human", "cancelled"].includes(task.status)) {
      throw new Error(`Task ${task.id} cannot be recovered from ${task.status}`);
    }
    task.startedAt = null;
    task.completedAt = null;
    task.updatedAt = this.support.now();
    await this.deps.tasks.save(task);
    return this.support.transitionTask(task, "queued", reason, operator);
  }

  async cancelTask(id: string, operator = "system"): Promise<TitingTask> {
    const task = await this.getTask(id);
    return this.support.transitionTask(task, "cancelled", "Task cancelled", operator);
  }

  async listExecutions(taskId: string): Promise<ExecutionRecord[]> {
    return this.deps.executions.listByTask(taskId);
  }

  async listExecutionLogs(taskId: string): Promise<ExecutionLogRecord[]> {
    return this.deps.executionLogs.listByTask(taskId);
  }

  async listTaskTransitions(taskId: string): Promise<TaskTransition[]> {
    return this.deps.taskTransitions.listByTask(taskId);
  }

  async getTaskObservability(taskId: string): Promise<{
    schemaVersion: string;
    taskId: string;
    transitions: TaskTransition[];
    executionLogs: ExecutionLogRecord[];
  }> {
    await this.getTask(taskId);
    const [transitions, executionLogs] = await Promise.all([
      this.deps.taskTransitions.listByTask(taskId),
      this.deps.executionLogs.listByTask(taskId)
    ]);
    return {
      schemaVersion: TitingServices.OBSERVABILITY_SCHEMA_VERSION,
      taskId,
      transitions,
      executionLogs
    };
  }

  /**
   * 按 **traceId** 聚合跨任务数据：同 trace 下多任务（如 repair 重入）的执行、日志、评测与 repair goal。
   * 无任务时抛 `NotFoundError`。
   */
  async getTraceView(traceId: string): Promise<{
    schemaVersion: string;
    traceId: string;
    tasks: TitingTask[];
    transitions: TaskTransition[];
    executions: ExecutionRecord[];
    executionLogs: ExecutionLogRecord[];
    evalResults: EvalResult[];
    repairGoals: RepairGoal[];
  }> {
    const tasks = await this.deps.tasks.listByTraceId(traceId);
    if (tasks.length === 0) {
      throw new NotFoundError(`Trace ${traceId} not found`);
    }
    const [transitions, executionArtifacts] = await Promise.all([
      this.deps.taskTransitions.listByTraceId(traceId),
      Promise.all(tasks.map(async (task) => ({
        executions: await this.deps.executions.listByTask(task.id),
        executionLogs: await this.deps.executionLogs.listByTask(task.id),
        evalResults: await this.deps.evalResults.listByTask(task.id),
        repairGoal: await this.deps.repairGoals.getByTaskId(task.id)
      })))
    ]);
    return {
      schemaVersion: TitingServices.OBSERVABILITY_SCHEMA_VERSION,
      traceId,
      tasks,
      transitions,
      executions: executionArtifacts.flatMap((item) => item.executions),
      executionLogs: executionArtifacts.flatMap((item) => item.executionLogs),
      evalResults: executionArtifacts.flatMap((item) => item.evalResults),
      repairGoals: executionArtifacts.flatMap((item) => (item.repairGoal ? [item.repairGoal] : []))
    };
  }

  async listEvalResults(taskId: string): Promise<EvalResult[]> {
    return this.deps.evalResults.listByTask(taskId);
  }

  async getRepairGoal(taskId: string): Promise<RepairGoal | null> {
    return this.deps.repairGoals.getByTaskId(taskId);
  }

  async listAgents(): Promise<AgentRecord[]> {
    return this.deps.agents.list();
  }

  async upsertAgent(agent: AgentRecord): Promise<void> {
    await this.deps.agents.upsert(agent);
  }

  async heartbeatAgent(id: string, status?: AgentRecord["status"]): Promise<AgentRecord> {
    const agent = await this.support.requireAgent(id);
    if (status && !["idle", "busy"].includes(status)) {
      throw new Error(`Heartbeat cannot set agent ${id} to ${status}`);
    }
    if (agent.status === "disabled" || agent.status === "error") {
      throw new Error(`Agent ${id} cannot heartbeat while ${agent.status}`);
    }
    agent.status = status ?? (agent.status === "offline" ? "idle" : agent.status);
    agent.lastHeartbeatAt = this.support.now();
    agent.updatedAt = this.support.now();
    await this.deps.agents.upsert(agent);
    await this.support.publishAgentEvent("agent.heartbeat", "Agent heartbeat refreshed", agent);
    return agent;
  }

  async disableAgent(id: string): Promise<AgentRecord> {
    const agent = await this.support.requireAgent(id);
    if (agent.status === "busy") {
      throw new Error(`Agent ${id} cannot be disabled while busy`);
    }
    agent.status = "disabled";
    agent.updatedAt = this.support.now();
    await this.deps.agents.upsert(agent);
    await this.support.publishAgentEvent("agent.disabled", "Agent disabled", agent);
    return agent;
  }

  async enableAgent(id: string): Promise<AgentRecord> {
    const agent = await this.support.requireAgent(id);
    if (agent.status !== "disabled") {
      throw new Error(`Agent ${id} is not disabled`);
    }
    agent.status = "idle";
    agent.taskId = null;
    agent.lastHeartbeatAt = this.support.now();
    agent.updatedAt = this.support.now();
    await this.deps.agents.upsert(agent);
    await this.support.publishAgentEvent("agent.enabled", "Agent enabled", agent);
    return agent;
  }

  async recoverAgent(id: string): Promise<AgentRecord> {
    const agent = await this.support.requireAgent(id);
    if (!["offline", "error"].includes(agent.status)) {
      throw new Error(`Agent ${id} cannot be recovered from ${agent.status}`);
    }
    agent.status = "idle";
    agent.taskId = null;
    agent.lastHeartbeatAt = this.support.now();
    agent.updatedAt = this.support.now();
    await this.deps.agents.upsert(agent);
    await this.support.publishAgentEvent("agent.recovered", "Agent recovered", agent);
    return agent;
  }

  /** 读插件列表并逐项 `health()`，供 dashboard 与 readiness。 */
  async listPlugins() {
    const plugins = this.deps.runtime.list();
    return Promise.all(
      plugins.map(async (plugin) => ({
        id: plugin.id,
        kind: plugin.kind,
        priority: plugin.priority,
        capabilities: plugin.capabilities,
        health: await plugin.health()
      }))
    );
  }

  async listPluginConfigs() {
    return this.deps.pluginConfigs.list();
  }

  async upsertPluginConfig(input: {
    pluginId: string;
    kind: PluginConfig["kind"];
    enabled: boolean;
    priority: number;
    config: Record<string, unknown>;
  }) {
    const existing = await this.deps.pluginConfigs.getByPluginId(input.pluginId);
    const config = {
      id: existing?.id ?? this.support.createId(),
      pluginId: input.pluginId,
      kind: input.kind,
      enabled: input.enabled,
      priority: input.priority,
      config: input.config,
      updatedAt: this.support.now()
    };
    await this.deps.pluginConfigs.upsert(config);
    await this.support.publishEvent({
      correlation: this.support.buildCorrelation({
        traceId: `plugin:${config.pluginId}`,
        pluginId: config.pluginId
      }),
      eventType: "plugin.config_updated",
      message: "Plugin config updated",
      data: {
        kind: config.kind,
        enabled: config.enabled,
        priority: config.priority
      }
    });
    return config;
  }

  async dashboard() {
    const tasks = await this.deps.tasks.list();
    const agents = await this.deps.agents.list();
    const plugins = await this.listPlugins();
    const statusCounts = countBy(tasks.map((task) => task.status));
    return {
      tasks: {
        total: tasks.length,
        byStatus: statusCounts
      },
      agents: {
        total: agents.length,
        byStatus: countBy(agents.map((agent) => agent.status))
      },
      plugins: {
        total: plugins.length,
        healthy: plugins.filter((plugin) => plugin.health.healthy).length
      }
    };
  }

  /** 定时器入口：同步集成 → 恢复离线 Agent/任务 → 派发队列。 */
  async runSchedulerTick(): Promise<void> {
    await this.schedulerEngine.runSchedulerTick();
  }

  async runTaskSyncNow(): Promise<{ integrations: number; pulledTasks: number }> {
    return this.schedulerEngine.runTaskSyncNow();
  }

  async runSchedulerDispatchNow(): Promise<{ queuedBefore: number }> {
    return this.schedulerEngine.runSchedulerDispatchNow();
  }

  async syncTaskIntegrations(): Promise<void> {
    await this.schedulerEngine.syncTaskIntegrations();
  }

  async ingestTaskFromIntegration(task: TitingTask, operator: string): Promise<TitingTask | null> {
    return this.schedulerEngine.ingestTaskFromIntegration(task, operator);
  }
}
